#lang racket
(define (square x)
  (* x x))
(define (good-enough? guess x)
  (< (abs (- guess x)) 0.001))
(define (improve guess x)
  (avg guess (/ x guess)))
(define (avg x y)
  (/ (+ x y) 2))
(define (sqrt-iter guess x)
  (if (good-enough? (square guess) x)
      guess
      (sqrt-iter (improve guess x) x)))
(define (sqrt x)
  (sqrt-iter 1.0 x))