.SUFFIXES: .erl .beam

.erl.beam
        erlc -W $<

ERL = erl -boot start_clean

MODS = module1 module2 module3

all: complie
     ${ERL} -pa '/home/cai/this/dir' -s module1 start

compile: ${MODS:%=%.beam}

clean:
        rm -rf *beam erl_crash.dump